version: '3.8'

services:
  captive_portal:
    image: captive_portal_image
    container_name: cpi0
    volumes:
    - /var/log/cp/:/var/log
    - /apps/wifi_portal/data:/apps/wifi_portal/data
    ports:
      - "8002:8001"
