services:
  wifi:
    build:
      context: ../
      x-bake: true
    container_name: wifi
    expose:
      - 80
    volumes:
      - /var/log/wifi/:/app/log/logs
    env_file:
      - .env
    networks:
      - wifi_portal

  mariadb:
    image: mariadb
    container_name: mariadb-wifi
    expose:
      - 3306
    volumes:
      - wifi-portal-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wifi_portal

  nginx:
    build:
      context: ./nginx/
      x-bake: true
    container_name: nginx-wifi
    ports:
      - "8000:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - wifi_portal

volumes:
  wifi-portal-volume:
    name: wifi-portal-volume

networks:
  wifi_portal:
    external: true
