services:
  wifi-portal:
    image: wifi_portal_image
    container_name: portal1
    volumes:
      - /var/log/wifi/:/app/log/logs
    ports:
      - "8002:8001"
    environment:
      - TZ=Africa/Nairobi  # Set Nairobi timezone explicitly
      # Kopo Kopo Keys
      - KOPOKOPO_API=https://api.kopokopo.com/
      - CLIENT_ID=MFH-VpZeD7iKjH0XsDPL5yAYb6ASszoYW8t6Xr8R8AA
      - CLIENT_SECRET=hJbYJ3sUmIuMb1lDPKLg92h0UNrhIFsDGQmIOE8YfQc
      # Maria DB Variables
      - MARIADB_HOST=mariadb
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=Admin1234
      - MARIADB_DATABASE=wifi
    networks:
      - wifi_portal

  mariadb:
    image: mariadb
    container_name: mariadb
    expose:
        - 3306
    volumes:
      - wifi-portal-volume:/var/lib/mysql
    environment:
      - TZ=Africa/Nairobi  # Set Nairobi timezone explicitly
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=Admin1234
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=wifi
    networks:
      - wifi_portal

volumes:
  wifi-portal-volume:
    name: wifi-portal-volume

networks:
  wifi_portal:
    external: true

